### PR TITLE
Fix breakage

### PR DESCRIPTION
**Pull request by stefansundin**
Looks like the extension has been broken for a few months. I have been using a heavily modified version for a while, which is why I didn't notice until now. I tried to break out my changes into multiple commits to make it easier to review.

Here are the big changes:
- Co-exist with the new "copy to clipboard" button.
- Update to the new row/column placement.
- Try to re-add links on mouse click and keyup.
- Re-add links on-the-fly if options are updated (using the popup).
- Add CoreOS username to list of amis.
- Remove jquery.

Hope you like it!

P.S. By the way, I have not tested Windows/RDP.

### CODE REVIEW

**Comment by stefanwork** [comment]
By the way, I have not tested Windows/RDP.

**Comment by stefansundin** [comment]
Hey @natefox. Let me know if this looks good or not. :)

**Comment by emz00** [comment]
It would be great to get this merged and released. The copy icon popping up is *really* annoying! I've copied the hostname to clipboard so many times when I meant to SSH/RDP to the host.

**Comment by natefox** [comment]
Finally getting back to this. My sincerest apologies.
I cant thank you enough for your help here. I'll be making some time to do additional updates.

**Comment by emz00** [comment]
It works - the link finally doesn't move around when the copy button pops up, thanks a lot @stefansundin! (And thanks for merging, @natefox.)

**Pull request merged**
